RedirectMatch 301 ^/TE-$ /TE-/

Alias /TE-/ "/app/tekg/app/"

<Directory "/app/tekg/app/">
    Options FollowSymLinks
    AllowOverride None
    Require all granted
    DirectoryIndex index.php

    <FilesMatch "(^\.|^config\.local\.php$)">
        Require all denied
    </FilesMatch>
</Directory>

