server.directories.data=/app/tekg/shared/neo4j-data
server.directories.logs=/app/tekg/shared/logs/neo4j
server.directories.run=/app/tekg/shared/neo4j-run
server.directories.import=/app/tekg/shared/neo4j-import
server.directories.dumps.root=/data/tekg/staging/neo4j

initial.dbms.default_database=tekg3
dbms.security.auth_enabled=true

server.default_listen_address=127.0.0.1
server.bolt.enabled=true
server.bolt.listen_address=127.0.0.1:7687
server.http.enabled=true
server.http.listen_address=127.0.0.1:7474
server.https.enabled=false

server.memory.heap.initial_size=1g
server.memory.heap.max_size=1g
server.memory.pagecache.size=512m

