[program:tekg-neo4j]
command=/app/tekg/services/neo4j-current/bin/neo4j console
directory=/app/tekg/services/neo4j-current
user=tekg_ro
environment=JAVA_HOME="/usr/lib/jvm/java-21-openjdk-amd64",NEO4J_HOME="/app/tekg/services/neo4j-current",NEO4J_CONF="/app/tekg/shared/config/neo4j"
autostart=true
autorestart=unexpected
startsecs=10
startretries=3
stopsignal=TERM
stopwaitsecs=120
stopasgroup=true
killasgroup=true
stdout_logfile=/app/tekg/shared/logs/neo4j/supervisor.log
stderr_logfile=/app/tekg/shared/logs/neo4j/supervisor.err

