<?php
declare(strict_types=1);

return [
    'understanding_result.v1' => [
        'version' => 'understanding_result.v1',
        'stage' => 'understanding',
        'type' => 'object',
        'required' => [
            'schema_version',
            'stage',
            'language',
            'question_summary',
            'intent',
            'entities',
            'ambiguities',
            'mode_boundary',
            'required_evidence',
            'warnings',
        ],
        'properties' => [
            'schema_version' => ['type' => 'string', 'const' => 'understanding_result.v1'],
            'stage' => ['type' => 'string', 'const' => 'understanding'],
            'language' => ['type' => 'string', 'enum' => ['zh', 'en']],
            'question_summary' => ['type' => 'string'],
            'intent' => ['type' => 'string'],
            'entities' => ['type' => 'array'],
            'ambiguities' => ['type' => 'array'],
            'mode_boundary' => ['type' => 'string'],
            'required_evidence' => ['type' => 'array'],
            'warnings' => ['type' => 'array'],
        ],
    ],
    'research_plan.v1' => [
        'version' => 'research_plan.v1',
        'stage' => 'planning',
        'type' => 'object',
        'required' => [
            'schema_version',
            'stage',
            'research_goal',
            'evidence_dimensions',
            'plugin_route',
            'required_plugins',
            'optional_plugins',
            'success_criteria',
            'risks',
        ],
        'properties' => [
            'schema_version' => ['type' => 'string', 'const' => 'research_plan.v1'],
            'stage' => ['type' => 'string', 'const' => 'planning'],
            'research_goal' => ['type' => 'string'],
            'evidence_dimensions' => ['type' => 'array'],
            'plugin_route' => ['type' => 'array'],
            'required_plugins' => ['type' => 'array'],
            'optional_plugins' => ['type' => 'array'],
            'success_criteria' => ['type' => 'array'],
            'risks' => ['type' => 'array'],
        ],
    ],
    'collection_decision.v1' => [
        'version' => 'collection_decision.v1',
        'stage' => 'collecting',
        'type' => 'object',
        'required' => [
            'schema_version',
            'stage',
            'is_sufficient',
            'missing_dimensions',
            'next_plugin',
            'stop_reason',
            'evidence_gaps',
            'decision_rationale',
        ],
        'properties' => [
            'schema_version' => ['type' => 'string', 'const' => 'collection_decision.v1'],
            'stage' => ['type' => 'string', 'const' => 'collecting'],
            'is_sufficient' => ['type' => 'boolean'],
            'missing_dimensions' => ['type' => 'array'],
            'next_plugin' => ['type' => ['string', 'null']],
            'stop_reason' => ['type' => ['string', 'null']],
            'evidence_gaps' => ['type' => 'array'],
            'decision_rationale' => ['type' => 'string'],
        ],
    ],
    'tool_execution_review.v1' => [
        'version' => 'tool_execution_review.v1',
        'stage' => 'executing',
        'type' => 'object',
        'required' => [
            'schema_version',
            'stage',
            'plugin_name',
            'plugin_result',
            'review_status',
            'usable',
            'evidence_summary',
            'caveats',
            'normalized_findings',
        ],
        'properties' => [
            'schema_version' => ['type' => 'string', 'const' => 'tool_execution_review.v1'],
            'stage' => ['type' => 'string', 'const' => 'executing'],
            'plugin_name' => ['type' => 'string'],
            'plugin_result' => ['type' => 'object'],
            'review_status' => ['type' => 'string', 'enum' => ['reviewed', 'not_required']],
            'review_not_required_reason' => ['type' => 'string'],
            'usable' => ['type' => 'boolean'],
            'evidence_summary' => ['type' => 'string'],
            'caveats' => ['type' => 'array'],
            'normalized_findings' => ['type' => 'array'],
        ],
        'conditional_required' => [
            [
                'if' => ['review_status' => 'not_required'],
                'required' => ['review_not_required_reason'],
            ],
        ],
    ],
    'claim_evidence_map.v1' => [
        'version' => 'claim_evidence_map.v1',
        'stage' => 'integrating',
        'type' => 'object',
        'required' => [
            'schema_version',
            'stage',
            'claims',
            'evidence_links',
            'unsupported_claims',
            'conflicts',
            'limitations',
            'integrity_notes',
        ],
        'properties' => [
            'schema_version' => ['type' => 'string', 'const' => 'claim_evidence_map.v1'],
            'stage' => ['type' => 'string', 'const' => 'integrating'],
            'claims' => ['type' => 'array'],
            'evidence_links' => ['type' => 'array'],
            'unsupported_claims' => ['type' => 'array'],
            'conflicts' => ['type' => 'array'],
            'limitations' => ['type' => 'array'],
            'integrity_notes' => ['type' => 'array'],
        ],
    ],
    'writing_decision.v1' => [
        'version' => 'writing_decision.v1',
        'stage' => 'writing',
        'type' => 'object',
        'required' => [
            'schema_version',
            'stage',
            'writing_strategy',
            'required_sections',
            'forbidden_claims',
            'citation_requirements',
            'tone',
            'final_checks',
        ],
        'properties' => [
            'schema_version' => ['type' => 'string', 'const' => 'writing_decision.v1'],
            'stage' => ['type' => 'string', 'const' => 'writing'],
            'writing_strategy' => ['type' => 'string'],
            'required_sections' => ['type' => 'array'],
            'forbidden_claims' => ['type' => 'array'],
            'citation_requirements' => ['type' => 'array'],
            'tone' => ['type' => 'string'],
            'final_checks' => ['type' => 'array'],
        ],
    ],
];
