<?php
declare(strict_types=1);

return [
    'routes' => [
        'search_summary' => [
            'title' => 'Search summary',
            'capability' => 'search_summary',
            'path' => 'search.php',
            'params' => 'te_search',
            'fragment' => 'search-summary-panel',
            'description' => 'Overview card for the selected TE.',
        ],
        'local_graph' => [
            'title' => 'Local graph',
            'capability' => 'local_graph',
            'path' => 'search.php',
            'params' => 'te_search',
            'fragment' => 'search-graph-panel',
            'description' => 'Local relationship graph around the selected TE.',
        ],
        'sequence' => [
            'title' => 'Sequence',
            'capability' => 'sequence',
            'path' => 'search.php',
            'params' => 'te_search',
            'fragment' => 'search-sequence-panel',
            'description' => 'Consensus sequence and sequence metadata.',
        ],
        'genome_distribution' => [
            'title' => 'Genome Annotation Distribution',
            'capability' => 'genome_distribution',
            'path' => 'search.php',
            'params' => 'te_search',
            'fragment' => 'search-karyotype-panel',
            'description' => 'Genome annotation distribution panel.',
        ],
        'genome_browser' => [
            'title' => 'Genome Browser',
            'capability' => 'genome_browser',
            'path' => 'search.php',
            'params' => 'te_search',
            'fragment' => 'search-jbrowse-panel',
            'description' => 'Embedded Genome Browser entry from the search detail page.',
        ],
        'jbrowse_direct' => [
            'title' => 'JBrowse direct entry',
            'capability' => 'genome_browser',
            'path' => 'jbrowse.php',
            'params' => 'te_param',
            'fragment' => '',
            'description' => 'Direct genome browser page.',
        ],
        'expression_summary' => [
            'title' => 'Expression detail summary',
            'capability' => 'expression',
            'path' => 'expression_detail.php',
            'params' => 'te_param',
            'fragment' => 'expression-detail-summary',
            'description' => 'Expression detail overview for the selected TE.',
        ],
        'expression_normal_tissue' => [
            'title' => 'Normal tissue expression',
            'capability' => 'expression',
            'path' => 'expression_detail.php',
            'params' => 'te_param',
            'fragment' => 'expression-detail-normal-tissue',
            'description' => 'Normal tissue expression panel.',
        ],
        'expression_normal_cell_line' => [
            'title' => 'Normal cell line expression',
            'capability' => 'expression',
            'path' => 'expression_detail.php',
            'params' => 'te_param',
            'fragment' => 'expression-detail-normal-cell-line',
            'description' => 'Normal cell line expression panel.',
        ],
        'expression_cancer_cell_line' => [
            'title' => 'Cancer cell line expression',
            'capability' => 'expression',
            'path' => 'expression_detail.php',
            'params' => 'te_param',
            'fragment' => 'expression-detail-cancer-cell-line',
            'description' => 'Cancer cell line expression panel.',
        ],
        'browse_catalog' => [
            'title' => 'Browse catalog',
            'capability' => 'browse',
            'path' => 'browse.php',
            'params' => 'none',
            'fragment' => '',
            'description' => 'Catalog page for TE browsing and filtering.',
        ],
        'preview_graph' => [
            'title' => 'TE-KG graph',
            'capability' => 'graph',
            'path' => 'preview.php',
            'params' => 'query_param',
            'fragment' => '',
            'description' => 'Interactive TE-KG graph preview.',
        ],
        'download' => [
            'title' => 'Download datasets',
            'capability' => 'download',
            'path' => 'download.php',
            'params' => 'none',
            'fragment' => '',
            'description' => 'Dataset download page.',
        ],
        'genomic' => [
            'title' => 'Genomic overview',
            'capability' => 'genomic',
            'path' => 'genomic.php',
            'params' => 'none',
            'fragment' => '',
            'description' => 'General genomic analysis page.',
        ],
    ],
    'capability_keywords' => [
        'genome_distribution' => ['Genome Annotation Distribution', 'annotation distribution', 'karyotype', 'genome distribution', '基因组注释分布', '注释分布', '基因组分布'],
        'genome_browser' => ['Genome Browser', 'JBrowse', 'browser', '基因组浏览器', '浏览器'],
        'sequence' => ['sequence', 'consensus', 'Repbase', 'full sequence', '完整序列', '序列'],
        'expression_normal_tissue' => ['normal tissue', 'tissue expression', '组织表达', '组织'],
        'expression_normal_cell_line' => ['normal cell line', 'cell line', '正常细胞系', '细胞系'],
        'expression_cancer_cell_line' => ['cancer cell line', 'cancer expression', '癌细胞系', '癌症细胞系'],
        'expression_summary' => ['expression', 'Expression page', '表达'],
        'preview_graph' => ['TE-KG', 'knowledge graph', 'graph page', '图谱', '知识图谱'],
        'local_graph' => ['local graph', 'relationship graph', '关系图', '局部图'],
        'browse_catalog' => ['browse', 'catalog', '目录', '浏览'],
        'download' => ['download', 'dataset', 'datasets', '下载', '数据集'],
        'search_summary' => ['search', 'summary', 'overview', '搜索', '概览', '简介'],
    ],
    'candidate_routes' => [
        'genome_distribution' => ['genome_distribution', 'genome_browser', 'jbrowse_direct', 'search_summary', 'preview_graph'],
        'genome_browser' => ['genome_browser', 'jbrowse_direct', 'genome_distribution', 'genomic', 'search_summary'],
        'sequence' => ['sequence', 'search_summary', 'browse_catalog', 'preview_graph'],
        'expression_normal_tissue' => ['expression_normal_tissue', 'expression_summary', 'expression_normal_cell_line', 'expression_cancer_cell_line'],
        'expression_normal_cell_line' => ['expression_normal_cell_line', 'expression_summary', 'expression_normal_tissue', 'expression_cancer_cell_line'],
        'expression_cancer_cell_line' => ['expression_cancer_cell_line', 'expression_summary', 'expression_normal_cell_line', 'expression_normal_tissue'],
        'expression_summary' => ['expression_summary', 'expression_normal_tissue', 'expression_normal_cell_line', 'expression_cancer_cell_line'],
        'preview_graph' => ['preview_graph', 'local_graph', 'search_summary'],
        'local_graph' => ['local_graph', 'preview_graph', 'search_summary'],
        'browse_catalog' => ['browse_catalog', 'search_summary', 'preview_graph'],
        'download' => ['download', 'browse_catalog', 'search_summary'],
        'default' => ['search_summary', 'sequence', 'genome_distribution', 'expression_summary', 'preview_graph'],
    ],
    'intent_fallbacks' => [
        'sequence' => 'sequence',
        'genome' => 'genome_browser',
        'expression' => 'expression_summary',
        'classification' => 'browse_catalog',
        'relationship' => 'preview_graph',
        'mechanism' => 'preview_graph',
        'comparison' => 'preview_graph',
        'default' => 'search_summary',
    ],
];
