EXTRA_TE_ALIASES = {
    "line1": "LINE1",
    "line-1": "LINE1",
    "line 1": "LINE1",
    "l1": "LINE1",
    "long interspersed element-1": "LINE1",
    "long interspersed nuclear element-1": "LINE1",
    "human line-1": "LINE1",
    "human line1": "LINE1",
}


EXTRA_DISEASE_ALIASES = {
    "aids": "Acquired immunodeficiency syndrome (AIDS)",
    "acquired immunodeficiency syndrome": "Acquired immunodeficiency syndrome (AIDS)",
    "acquired immunodeficiency syndrome (aids)": "Acquired immunodeficiency syndrome (AIDS)",
    "als": "Amyotrophic lateral sclerosis (ALS)",
    "amyotrophic lateral sclerosis": "Amyotrophic lateral sclerosis (ALS)",
    "amyotrophic lateral sclerosis (als)": "Amyotrophic lateral sclerosis (ALS)",
    "huntington disease": "Huntington's disease",
    "ftd": "Frontotemporal dementia",
    "frontotemporal dementia": "Frontotemporal dementia",
    "frontotemporal dementia (ftd)": "Frontotemporal dementia",
    "hnscc": "Head and neck squamous cell carcinoma",
    "head and neck squamous cell carcinoma": "Head and neck squamous cell carcinoma",
    "head and neck squamous cell carcinoma (hnscc)": "Head and neck squamous cell carcinoma",
    "lscc": "lung squamous cell carcinoma",
    "lung squamous cell carcinoma": "lung squamous cell carcinoma",
    "lung squamous cell carcinoma (lscc)": "lung squamous cell carcinoma",
    "tle": "Temporal lobe epilepsy (TLE)",
    "temporal lobe epilepsy": "Temporal lobe epilepsy (TLE)",
    "temporal lobe epilepsy (tle)": "Temporal lobe epilepsy (TLE)",
    "ucec": "Uterine corpus endometrial carcinoma (UCEC)",
    "uterine corpus endometrial carcinoma": "Uterine corpus endometrial carcinoma (UCEC)",
    "uterine corpus endometrial carcinoma (ucec)": "Uterine corpus endometrial carcinoma (UCEC)",
    "mendelian diseases": "Mendelian disease",
    "mendelian disorders": "Mendelian disease",
    "genetic disorders": "genetic disease",
    "human genetic disorders": "human genetic disease",
    "neurogenetic disorders": "neurogenetic disease",
    "ebv-associated gastric cancer": "Epstein-Barr virus-associated gastric cancer",
    "h3 k27m-mutant diffuse midline gliomas": "H3 K27M-mutant diffuse midline glioma",
    "hiv-associated neurocognitive disorder (hand)": "HIV-associated neurocognitive disorder",
    "x-linked dystonia-parkinsonism (xdp, dyt3)": "X-linked dystonia parkinsonism (XDP)",
    "serous tubal intraepithelial carcinomas (stics)": "serous tubal intraepithelial carcinoma (STIC)",
    "single-gene diseases": "single-gene disease",
    "genomic disorders": "genomic disease",
    "neuropsychiatric diseases": "neuropsychiatric disease",
    "early spontaneous miscarriage": "early spontaneous abortion",
    "spontaneous genetic diseases": "Spontaneous Genetic Disorder",
    "early pregnancy loss (epl)": "early spontaneous abortion",
    "monogenic disease": "single-gene disease",
    "de novo genetic diseases": "Spontaneous Genetic Disorder",
    "heritable disease": "human genetic disease",
    "inherited genetic diseases": "human genetic disease",
    "inherited human diseases": "human genetic disease",
    "neurological and psychiatric diseases": "neuropsychiatric disease",
    "hiv-1 infection": "HIV infection",
    "psychiatric diseases": "psychiatric disorders",
    "genetic instability": "genomic instability",
    "becker muscular dystrophy (bmd)": "Becker muscular dystrophy",
    "duchenne muscular dystrophy (dmd)": "Duchenne muscular dystrophy",
    "chronic fatigue syndrome": "Myalgic Encephalomyelitis/Chronic Fatigue Syndrome",
    "myalgic encephalomyelitis": "Myalgic Encephalomyelitis/Chronic Fatigue Syndrome",
    "htlv-1-associated myelopathy (ham)": "HTLV-1-associated myelopathy/tropical spastic paraparesis (HAM/TSP)",
    "htlv-1-associated myelopathy(ham)": "HTLV-1-associated myelopathy/tropical spastic paraparesis (HAM/TSP)",
    "tropical spastic paraparesis (tsp)": "HTLV-1-associated myelopathy/tropical spastic paraparesis (HAM/TSP)",
    "mosaic variegated aneuploidy (mva) syndrome": "premature chromatid separation (PCS)/mosaic variegated aneuploidy (MVA) syndrome",
    "premature chromatid separation (pcs)": "premature chromatid separation (PCS)/mosaic variegated aneuploidy (MVA) syndrome",
}


EXTRA_FUNCTION_ALIASES = {
    "insertion mutation": "insertional mutation",
    "insertion mutations": "insertional mutation",
    "insertional mutations": "insertional mutation",
    "a-to-i editing": "A-to-I RNA editing",
    "adenosine-to-inosine editing": "A-to-I RNA editing",
    "interferon production": "Interferon (IFN) production",
    "type i interferon induction": "Type I interferon response",
    "type-i interferon (ifn-i) response": "Type I interferon response",
    "type i interferon signaling": "Type I interferon response",
    "type-i interferon response": "Type I interferon response",
    "type i interferon system activation": "Type I interferon response",
    "interferon signaling": "Interferon response",
    "interferon signaling activation": "Interferon response",
    "interferon system activation": "Interferon response",
    "3' dna transduction": "3' transduction",
    "5' and 3' transductions": "5' and 3' transduction",
    "dna transduction": "Sequence transduction",
    "transduction": "Sequence transduction",
    "line retrotransposition": "LINE-1 retrotransposition",
    "l1 retrotransposition": "LINE-1 retrotransposition",
    "l1 retrotransposition (l1-rtp)": "LINE-1 retrotransposition",
    "l1-mediated retrotransposition": "LINE-1-mediated retrotransposition",
}
