<?php
declare(strict_types=1);
require_once dirname(__DIR__, 2) . '/api/coexpression_repository.php';
function check(bool $ok,string $message): void { if(!$ok) throw new RuntimeException($message); }
try {
  $source=file_get_contents(dirname(__DIR__,2).'/api/coexpression_repository.php') ?: '';
  foreach(['file_get_contents','fopen','realpath','data/coexpression','manifest.json','.tsv','.json'] as $forbidden) check(!str_contains($source,$forbidden),'Runtime repository must not read filesystem source: '.$forbidden);
  $db=tekg_expression_db(); $v=tekg_coexpression_active_version(); $id=(int)$v['id'];
  $counts=$db->query("SELECT (SELECT COUNT(*) FROM coexpression_analysis_versions WHERE is_active=1) versions,(SELECT COUNT(DISTINCT center_te) FROM coexpression_networks WHERE version_id=$id) tes,(SELECT COUNT(*) FROM coexpression_networks WHERE version_id=$id) networks,(SELECT COUNT(*) FROM coexpression_network_nodes n JOIN coexpression_networks w ON w.id=n.network_id WHERE w.version_id=$id) nodes,(SELECT COUNT(*) FROM coexpression_network_edges e JOIN coexpression_networks w ON w.id=e.network_id WHERE w.version_id=$id) edges")->fetch_assoc();
  check((int)$counts['versions']===1,'Expected one active version'); check((int)$counts['tes']===285,'Expected 285 TEs'); check((int)$counts['networks']===849,'Expected 849 networks');
  $bad=$db->query("SELECT COUNT(*) c FROM coexpression_network_edges e JOIN coexpression_networks w ON w.id=e.network_id LEFT JOIN coexpression_network_nodes s ON s.network_id=e.network_id AND s.node_id=e.source_id LEFT JOIN coexpression_network_nodes t ON t.network_id=e.network_id AND t.node_id=e.target_id WHERE w.version_id=$id AND (s.node_id IS NULL OR t.node_id IS NULL OR e.correlation<=0 OR e.fdr<0)")->fetch_assoc(); check((int)$bad['c']===0,'Invalid edge endpoint or numeric value');
  $root=dirname(__DIR__,2).'/data/coexpression/display_subgraphs/'.TEKG_COEXPRESSION_VERSION; $manifest=json_decode((string)file_get_contents($root.'/all_te/manifest.json'),true,512,JSON_THROW_ON_ERROR); $checked=0;
  foreach($manifest['files'] as $relative){$raw=json_decode((string)file_get_contents($root.'/'.$relative),true,512,JSON_THROW_ON_ERROR);$got=tekg_coexpression_load_network($raw['center'],$raw['context_type']); check(count($got['nodes'])===count($raw['nodes'])&&count($got['edges'])===count($raw['edges']),"Size parity failed for $relative"); check($got['module']['id']===$raw['module_id']&&$got['interpretation']['statement_en']===$raw['interpretation_statement_en'],"Metadata parity failed for $relative"); foreach($raw['nodes'] as $i=>$n) check($got['nodes'][$i]['id']===$n['id']&&$got['nodes'][$i]['role']===$n['role'],"Node order parity failed for $relative"); foreach($raw['edges'] as $i=>$e) check($got['edges'][$i]['source']===$e['source']&&$got['edges'][$i]['target']===$e['target']&&(float)$got['edges'][$i]['correlation']===(float)$e['correlation']&&(float)$got['edges'][$i]['fdr']===(float)$e['fdr'],"Edge parity failed for $relative");$checked++;}
  check($checked===849,'Full parity did not inspect all networks'); echo "PASS: MySQL co-expression contract and full 849-network parity ($counts[nodes] nodes, $counts[edges] edges)\n";
} catch(Throwable $e){fwrite(STDERR,'FAIL: '.$e->getMessage()."\n");exit(1);}
