<?php
return [
    'dashscope_key' => getenv('DASHSCOPE_API_KEY_BIOLOGY') ?: getenv('DASHSCOPE_API_KEY') ?: '',
    'dashscope_model' => 'deepseek-v4-flash',
    'agent_core_model' => 'deepseek-v4-pro',
    'agent_sufficiency_model' => 'deepseek-v4-pro',
    'agent_expert_model' => 'deepseek-v4-pro',
    'agent_narrator_model' => 'deepseek-v4-pro',
    'agent_answer_structure_model' => 'deepseek-v4-pro',
    'agent_writing_model' => 'deepseek-v4-pro',
    'agent_polisher_model' => 'deepseek-v4-pro',
    'deepseek_model' => 'deepseek-v4-flash',
    'deepseek_reasoner_model' => 'deepseek-v4-flash',
    'dashscope_url' => 'https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions',
    'ssl_verify' => false,
    'llm_relay_url' => 'http://127.0.0.1:18087/chat',
    'agent_execution_timeout' => 7200,
    'llm_narrator_timeout' => 60,
    'llm_json_timeout' => 120,
    'llm_six_stage_node_timeout' => 1200,
    'llm_answer_chat_timeout' => 1200,
    'llm_answer_reasoner_timeout' => 1200,
    'neo4j_url' => 'http://127.0.0.1:7474/db/tekg3/tx/commit',
    'neo4j_user' => 'neo4j',
    'neo4j_password' => 'xjss9577',
    'key_node_threshold' => 3,
    'key_node_expand_limit' => 20,
    'mysql_host' => '127.0.0.1',
    'mysql_port' => 3306,
    'mysql_expression_database' => 'tekg_expression',
    'mysql_user' => 'root',
    'mysql_password' => '',
    'mysql_charset' => 'utf8mb4',
];
